Repository ayushi-ras/JS-Game, pull requests merged in 2023-10, with the labels that each got.

#8 Adds pause functionality to the game:
  game.js
  style.css
Labels: enhancement, good first issue, hacktoberfest-accepted

#16 Update game.html
  game.html
Labels: hacktoberfest-accepted, hactoberfest

#17 done
  USER-DATABASE/CRUD_Application_Node/LICENSE
  USER-DATABASE/CRUD_Application_Node/README.md
  USER-DATABASE/CRUD_Application_Node/assets/css/style.css
  USER-DATABASE/CRUD_Application_Node/assets/js/index.js
  USER-DATABASE/CRUD_Application_Node/package-lock.json
  USER-DATABASE/CRUD_Application_Node/package.json
  USER-DATABASE/CRUD_Application_Node/server.js
  USER-DATABASE/CRUD_Application_Node/server/controller/controller.js
  USER-DATABASE/CRUD_Application_Node/server/database/connection.js
  USER-DATABASE/CRUD_Application_Node/server/model/model.js
  USER-DATABASE/CRUD_Application_Node/server/routes/router.js
  USER-DATABASE/CRUD_Application_Node/server/services/render.js
  USER-DATABASE/CRUD_Application_Node/views/add_user.ejs
  USER-DATABASE/CRUD_Application_Node/views/include/_footer.ejs
  USER-DATABASE/CRUD_Application_Node/views/include/_form.ejs
  USER-DATABASE/CRUD_Application_Node/views/include/_header.ejs
  USER-DATABASE/CRUD_Application_Node/views/include/_show.ejs
  USER-DATABASE/CRUD_Application_Node/views/index.ejs
  USER-DATABASE/CRUD_Application_Node/views/update_user.ejs
  USER-DATABASE/swastik
Labels: enhancement, hacktoberfest-accepted, hactoberfest

#18 Adds start game features
  game.js
Labels: enhancement, hacktoberfest-accepted, hactoberfest

#22 Update readme.md
  Images/readme_image.png
  README.md
Labels: documentation, hacktoberfest-accepted

#27 added Favicon to the game site
  Images/favicon/android-chrome-192x192.png
  Images/favicon/android-chrome-512x512.png
  Images/favicon/apple-touch-icon.png
  Images/favicon/favicon-16x16.png
  Images/favicon/favicon-32x32.png
  Images/favicon/favicon.ico
  game.html
Labels: bug, hacktoberfest-accepted, hactoberfest

#29 url fixes
  game.html
  game.js
Labels: bug, hacktoberfest-accepted, hactoberfest
